// auto-generated by get-my-vocadb-java-model at 2020-06-23T13:06:28.186114200
package mikufan.cx.common_vocaloid_entity.vocadb.api.songList.getListIdSongs;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import mikufan.cx.common_vocaloid_entity.vocadb.models.SongForApiContract;

@Getter @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SongInListForApiContract {

  @JsonProperty
  private String notes;

  @JsonProperty
  private int order;

  @JsonProperty
  private SongForApiContract song;

}
