// auto-generated by get-my-vocadb-java-model at 2020-06-23T13:06:28.220023100
package mikufan.cx.common_vocaloid_entity.vocadb.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ArtistContract {

  @JsonProperty
  private String additionalNames;

  @JsonProperty
  private String artistType;

  @JsonProperty
  private boolean deleted;

  @JsonProperty
  private int id;

  @JsonProperty
  private String name;

  @JsonProperty
  private String pictureMime;

  @JsonProperty
  private String releaseDate;

  @JsonProperty
  private String status;

  @JsonProperty
  private int version;

}
