// auto-generated by get-my-vocadb-java-model at 2020-06-23T13:06:28.218028700
package mikufan.cx.common_vocaloid_entity.vocadb.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OptionalDateTimeContract {

  @JsonProperty
  private int day;

  @JsonProperty
  private String formatted;

  @JsonProperty
  private boolean isEmpty;

  @JsonProperty
  private int month;

  @JsonProperty
  private int year;

}
