// auto-generated by get-my-vocadb-java-model at 2020-06-23T13:06:28.210054800
package mikufan.cx.common_vocaloid_entity.vocadb.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PVContract {

  @JsonProperty
  private String author;

  @JsonProperty
  private int createdBy;

  @JsonProperty
  private boolean disabled;

  @JsonProperty
  private PVExtendedMetadata extendedMetadata;

  @JsonProperty
  private int id;

  @JsonProperty
  private int length;

  @JsonProperty
  private String name;

  @JsonProperty
  private String publishDate;

  @JsonProperty
  private String pvId;

  @JsonProperty
  private String service;

  @JsonProperty
  private String pvType;

  @JsonProperty
  private String thumbUrl;

  @JsonProperty
  private String url;

}
