name: Remove old Package Versions
# from https://github.com/navikt/remove-package-versions
on:
  push:
    branches: master
#   schedule:
#     - cron:  '0 8 * * *'

jobs:
  remove-old-packages:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old common-vocaloid
      uses: actions/delete-package-versions@v1.0.2
      with:
        # Name of the package containing the version to delete. Required if dynamically deleting oldest versions.
        package-name: 'common-vocaloid' # optional
        # Number of versions to delete starting with the oldest version. Defaults to 1.
        num-old-versions-to-delete: 1 # optional, default is 1
     
     
    - name: Delete old common-vocaloid-import-all
      uses: actions/delete-package-versions@v1.0.2
      with:
        # Name of the package containing the version to delete. Required if dynamically deleting oldest versions.
        package-name: 'common-vocaloid-import-all' # optional
        # Number of versions to delete starting with the oldest version. Defaults to 1.
        num-old-versions-to-delete: 1 # optional, default is 1

    - name: Delete old common-vocaloid-entity
      uses: actions/delete-package-versions@v1.0.2
      with:
        # Name of the package containing the version to delete. Required if dynamically deleting oldest versions.
        package-name: 'common-vocaloid-entity' # optional
        # Number of versions to delete starting with the oldest version. Defaults to 1.
        num-old-versions-to-delete: 1 # optional, default is 1

    - name: Delete old common-vocaloid-util
      uses: actions/delete-package-versions@v1.0.2
      with:
        # Name of the package containing the version to delete. Required if dynamically deleting oldest versions.
        package-name: 'common-vocaloid-util' # optional
        # Number of versions to delete starting with the oldest version. Defaults to 1.
        num-old-versions-to-delete: 1 # optional, default is 1
 
