name: Remove old Package Versions
# from https://github.com/navikt/remove-package-versions
on:
  push:
    branches: master
#   schedule:
#     - cron:  '0 8 * * *'

jobs:
  remove-old-packages:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Package Versions
      uses: actions/delete-package-versions@v1.0.2
      with:
        num-old-versions-to-delete: 999
