name: Remove old Package Versions
# from https://github.com/navikt/remove-package-versions
on:
  push:
    branches: master
#   schedule:
#     - cron:  '0 8 * * *'
jobs:
  remove-old-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Remove package versions
        id: remove-package-versions
        uses: navikt/remove-package-versions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:  
          keep-versions: 1
