# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto-deploy on Github

on:
  repository_dispatch: # disabling this action as jitpack provide better deployment

# on:
#   push:
#     branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.11
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: | 
          ${{ runner.os }}-maven-

    - name: Setup settings.xml
      uses: whelk-io/maven-settings-xml-action@v7
      with:
        # json array of servers to add to settings.xml
        servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
        # json array of repositories to add to settings.xml
        repositories: '[{"id": "github", "url": "https://maven.pkg.github.com/CXwudi/common-vocaloid-java"}]'

    - name: Deploy to Github without Testing
      working-directory: all-in-one/
      run: mvn clean deploy -Dmaven.test.skip=true
